version: "3.4"
services:
  web:
    build: .
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ./mezzo
        target: /usr/src/app
    environment:
      - DEBUG
      - DB_PASSWORD
      - DB_USERNAME
      - DB_NAME

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=genius01
    volumes:
      - talentmob-data:/var/lib/postgresql/data
    ports:
      - "5443:5432"

volumes:
  talentmob-data:
    external: true

networks:
  default:
    external:
      name: talentmob
